[project]
name = "nerfac"
version = "0.1.0"

dependencies=[
    "nerfstudio==0.3.2"
]

[tool.setuptools.packages.find]
include = ["nerfac*"]

[project.entry-points.'nerfstudio.method_configs']
nerfac = 'nerfac.nerfac_config:nerfac_method'
